Remove unnecessary cache read
gql-dart/ferry pull request #179
Opened 2021-05-06 11:14 UTC by friebetill

While going through the timeline of my app, I noticed that every time I read the cache, the cache is read twice. This makes a noticeable effect on the UX of my users, so I am trying to remove the second cache read. (Ferry is on an isolate in my app, so the timelines is only from Ferry code)

#### Timeline with existing code

![image](https://user-images.githubusercontent.com/10923085/117283798-6f2c3f00-ae66-11eb-8038-ff1a52814de6.png)
The image above shows the timeline of one query with `CacheFirst`. The query takes about 500ms in total and consists of mainly 6 parts:
- the green block: `watchQuery (half)` is the timeline from this code in `cache.dart`:
   <details><summary>code</summary>
   <p>
   

   ```dart
   var closed = false;

   final dataChanged = operationDataChangeStream(
     request,
     optimistic,
     optimisticPatchesStream,
     optimisticReader,
     store,
     typePolicies,
     addTypename,
   ).doOnDone(() => closed = true);
   ```
    
   </p>
   </details>

- the orange block `cache.watchQuery readQuery` is the timeline from this code in `cache.dart`:

   <details><summary>code</summary>
   <p>
   
   ```dart
   readQuery(
     request,
     optimistic: optimistic,
   );
   ```
   </p>
   </details>

- the many small turquoise blocks `operationDataChangeStream. dataId map` is the timeline from this code in `operation_data_change_stream.dart`:

   <details><summary>code</summary>
   <p>

   ```dart
   var stream = dataForIdStream(
     dataId,
     store,
     optimistic,
     optimisticPatchesStream,
     optimisticReader,
   );

   /// we only want to subscribe to changes on the operation fields, not the entire operation type)
   if (dataId == rootTypename) {
     stream = stream.map(
       (data) => operationRootData(
         data,
         request,
         typePolicies,
       ),
     );
   }
   ```
   </p>
   </details>

- and the three parts again for the second cache read.

#### Timeline with code from this PR:
![image](https://user-images.githubusercontent.com/10923085/117288175-7efa5200-ae6b-11eb-8a7a-677ae6d28bd7.png)
The image above, shows the same CacheFirst query with the code from this PR. The query takes a total of 230ms, about half the time of the query above.

The two timelines can also be viewed in detail here [dart_timeline.zip](https://github.com/gql-dart/ferry/files/6433942/dart_timeline.zip), preferably via `chrome://tracing/` from a Chromium based browser, as the Flutter timeline viewer is slow.

#### Code
All tests are successful, but I am unsure if it is necessary to close the StreamController manually.

#### How to measure the timeline
To generate the timeline in Flutter Dev, I followed [this instructions](https://medium.com/flutter/profiling-flutter-applications-using-the-timeline-a1a434964af3) and used `Timeline.startSync` and `Timeline.finishSync` in the code to see specific code parts.

#### Another possibility for optimization:
I currently think that there is another problem with the `dataIds` in the file `operation_data_change_stream.dart`. Currently there are too many dataIds monitored for a small query. This is also visible in the timeline, these are the many small blue lines, which in total take quite a lot of time. I'll take a look at that soon and see if there's anything that can be optimized.

2021-05-06 13:43 UTC, smkhalsa requested changes
Thanks for the PR!

I know that there are a few places that performance could be improved, so this is much appreciated.

> I currently think that there is another problem with the dataIds in the file operation_data_change_stream.dart. There are too many dataIds monitored for a small query. This is also visible in the timeline, these are the many small turquoise lines, which in total take quite a lot of time. I'll take a look at that soon and see if there's anything that can be optimized.

That'd be great.

Out of curiosity, how many records are you reading in this example?

2021-05-06 13:43 UTC, smkhalsa commented on ferry/lib/src/fetch_policy_typed_link.dart
> +            .distinct();
Is the `distinct()` necessary to prevent network data written to the cache from triggering a second identical data event from the cache?

If so, this probably only worked because of [this](https://github.com/gql-dart/ferry/pull/180) oversight since responses with different DataSources should not be equal.

Can you please rebase?

2021-05-06 13:43 UTC, smkhalsa commented on ferry/lib/src/fetch_policy_typed_link.dart
> +        ]).distinct();
Same as above

2021-05-11 12:38 UTC, closed without merging

2021-05-13 16:09 UTC, smkhalsa commented
Looks like this was automatically closed when the target branch was merged into master. Feel free to re-open targeting master.

2021-05-13 16:16 UTC, friebetill commented
Ah, I understand and will hopefully reopen the PR soon. At the moment I'm still looking for the main problem why my app has big memory leaks and is very slow since the Flutter 2 update.